<?php

$liste_ecoles_autre = array(

/*  "a" => "orange", "b" => "banana", "c" => "apple" */

"Je ne suis plus &eacute;tudiant",
"Je ne suis pas encore &eacute;tudiant",
"Autre - Je ne trouve pas mon Ecole dans la liste ! (Le Master sera mis au courant !)"
);

$liste_ecoles_ingenieur = array(
/* Ecoles d'ing&eacute;nieur */

"Centre des &eacute;tudes sup&eacute;rieures industrielles	[16 - Angoul&ecirc;me]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[62 - Arras]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[33 - Bordeaux]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[69 - Lyon]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[54 - Nancy]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[75 - Paris]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[92 - Paris-Bagneux]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[64 - Pau]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[76 - Rouen]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[44 - Saint-Nazaire]",
"Centre des &eacute;tudes sup&eacute;rieures industrielles	[31 - Toulouse]", 

"Centre international d'&eacute;tudes sup&eacute;rieures en sciences agronomiques	[34 - Montpellier]",
"Centre universitaire Jean-Fran&ccedil;ois-Champollion	[81 - Castres]",
"Conservatoire national des arts et m&eacute;tiers	[00 - France]",
"Ecole Catholique des Arts et M&eacute;tiers	[67 - Strasbourg]",
"Ecole Catholique des Arts et M&eacute;tiers	[69 - Lyon]",

"Ecole Centrale d'&eacute;lectronique	[75 - Paris]",
"Ecole Centrale de Lille	[59 - Villeneuve-d'Ascq]",
"Ecole Centrale de Lyon		[69 - &eacute;cully]",
"Ecole Centrale de Marseille	[13 - Marseille]",
"Ecole Centrale de Nantes	[44 - Nantes]",
"Ecole Centrale de Paris		[92 - Ch&acirc;tenay-Malabry]",

"Ecole d'ing&eacute;nieur d'agro-d&eacute;veloppement international	[95 - Cergy-Pontoise]",
"Ecole d'ing&eacute;nieurs de Purpan	[31 - Toulouse]",
"Ecole d'ing&eacute;nieurs du Littoral C&ocirc;te d'Opale	[59 - Dunkerque]",
"Ecole d'ing&eacute;nieurs du Pas-de-Calais	[62 - Longuenesse]",
"Ecole d'ing&eacute;nieurs en g&eacute;nie des syst&egrave;mes industriels	[17 - La Rochelle]",

"Ecole d'&eacute;lectricit&eacute;, de production et des m&eacute;thodes industrielles	[95 - Cergy-Pontoise]",
"Ecole de biologie industrielle		[95 - Cergy-Pontoise]",
"Ecole de l'air		[13 - Salon-de-Provence]",
"Ecole des ing&eacute;nieurs de la ville de Paris	[75 - Paris]",

"Ecole des Mines d'Albi-Carmaux		[81 - Albi]",
"Ecole des Mines d'Al&egrave;s		[30 - Al&egrave;s]",
"Ecole des Mines de Douai	[59 - Douai]",
"Ecole des Mines de Nantes	[44 - Nantes]",
"Ecole des Mines ParisTech	[75 - Paris]",
"Ecole des Mines de Nancy	[54 - Nancy]",
"Ecole des Mines de Saint-Di&eacute;	[88 - Saint-Di&eacute;]",
"Ecole des Mines de Saint-&eacute;tienne	[42 - Saint-&eacute;tienne]",
"Ecole des Mines de Gardanne	[13 - Gardanne]",

"Ecole des m&eacute;tiers de l'environnement	[35 - Bruz]",
"Ecole des transmissions	[35 - Cesson-S&eacute;vign&eacute;]",
"Ecole du g&eacute;nie		[49 - Angers]",
"Ecole et observatoire des sciences de la Terre		[67 - Strasbourg]",
"Ecole europ&eacute;enne d'ing&eacute;nieurs en g&eacute;nie des mat&eacute;riaux	[54 - Nancy]",
"Ecole europ&eacute;enne de chimie, polym&egrave;res et mat&eacute;riaux	[67 - Strasbourg]",
"Ecole fran&ccedil;aise d'&eacute;lectronique et d'informatique	[94 - Villejuif]",
"Ecole internationale des sciences du traitement de l'information	[95 - Cergy-Pontoise]",
"Ecole internationale des sciences du traitement de l'information	[64 - Pau]",
"Ecole internationale du papier, de la communication imprim&eacute;e et des biomat&eacute;riaux	[38 - Grenoble]",

"Ecole Louis de Broglie		[35 - Bruz]",
"Ecole nationale d'ing&eacute;nieurs de Brest	[29 - Brest]",
"Ecole nationale d'ing&eacute;nieurs de Metz	[57 - Metz]",
"Ecole nationale d'ing&eacute;nieurs de Saint-&eacute;tienne	[42 - Saint-&eacute;tienne]",
"Ecole nationale d'ing&eacute;nieurs de Tarbes	[65 - Tarbes]",
"Ecole nationale d'ing&eacute;nieurs du Val de Loire	[41 - Blois]",

"Ecole nationale de l'aviation civile	[31 - Toulouse]",

"Ecole nationale de la m&eacute;t&eacute;orologie	[31 - Toulouse]",

"Ecole nationale de la statistique et de l'administration &eacute;conomique	[92 - Malakoff]",
"Ecole nationale de la statistique et de l'analyse de l'information	[35 - Bruz]",

"Ecole nationale des ponts et chauss&eacute;es		[77 - Marne-la-Vall&eacute;e]",

"Ecole nationale des sciences g&eacute;ographiques	[77 - Marne-la-Vall&eacute;e]",
"Ecole nationale des travaux publics de l'&eacute;tat	[69 - Vaulx-en-Velin]",
"Ecole nationale du g&eacute;nie de l'eau et de l'environnement de Strasbourg		[67 - Strasbourg]",
"Ecole nationale sup&eacute;rieure agronomique de Toulouse	[31 - Castanet-Tolosan]",
"Ecole nationale sup&eacute;rieure d'agronomie et des industries alimentaires	[54 - Vandœuvre]",

"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[49 - Angers]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[13 - Aix-en-provence]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[33 - Bordeaux-Talence]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[51 - Ch&acirc;lons-en-Champagne]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[71 - Cluny]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[59 - Lille]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[57 - Metz]",
"Ecole nationale sup&eacute;rieure d'arts et m&eacute;tiers	[75 - Paris]",

"Ecole nationale sup&eacute;rieure d'informatique et de math&eacute;matiques appliqu&eacute;es de Grenoble	[38 - Saint-Martin-d'H&egrave;res]",
"Ecole nationale sup&eacute;rieure d'informatique pour l'industrie et l'entreprise	[91 - &eacute;vry]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Bourges	[18 - Bourges]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Bretagne sud	[56 - Lorient]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Bretagne sud	[56 - Vannes]",

"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Caen	[14 - Caen]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Flers	[61 - Flers]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Limoges	[87 - Limoges]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs de Poitiers	[86 - Poitiers]",
"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs du Mans	[72 - Le Mans]",

"Ecole nationale sup&eacute;rieure d'ing&eacute;nieurs en informatique automatique m&eacute;canique &eacute;nerg&eacute;tique &eacute;lectronique		[59 - Valenciennes]",
"Ecole nationale sup&eacute;rieure d'&eacute;lectricit&eacute; et de m&eacute;canique	[54 - Vandœuvre]",
"Ecole nationale sup&eacute;rieure d'&eacute;lectronique, informatique, t&eacute;l&eacute;communications, math&eacute;matiques et m&eacute;canique de Bordeaux		[33 - Talence]",
"Ecole nationale sup&eacute;rieure d'&eacute;lectrotechnique, d'&eacute;lectronique, d'informatique, d'hydraulique et des t&eacute;l&eacute;communications		[31 - Toulouse]",

"Ecole nationale sup&eacute;rieure de chimie de Clermont-Ferrand	[63 - Aubi&egrave;re]",
"Ecole nationale sup&eacute;rieure de chimie de Lille			[59 - Villeneuve-d'Ascq]",
"Ecole nationale sup&eacute;rieure de chimie de Montpellier		[34 - Montpellier]",
"Ecole nationale sup&eacute;rieure de chimie de Mulhouse		[68 - Mulhouse]",
"Ecole nationale sup&eacute;rieure de chimie de Paris			[75 - Paris]",
"Ecole nationale sup&eacute;rieure de chimie de Rennes			[35 - Rennes]",
"Ecole nationale sup&eacute;rieure de chimie, de biologie et de physique	[33 - Pessac]",

"Ecole nationale sup&eacute;rieure de cognitique	[33 - Bordeaux]",
"Ecole nationale sup&eacute;rieure de c&eacute;ramique industrielle	[87 - Limoges]",
"Ecole nationale sup&eacute;rieure de g&eacute;nie industriel		[38 - Grenoble]",
"Ecole nationale sup&eacute;rieure de g&eacute;ologie		[54 - Vandœuvre]",
"Ecole nationale sup&eacute;rieure de l'&eacute;lectronique et de ses applications	[95 - Cergy-Pontoise]",
"Ecole nationale sup&eacute;rieure de l'&eacute;nergie, l'eau et l'environnement	[38 - Grenoble]",
"Ecole nationale sup&eacute;rieure de la nature et du paysage		[41 - Blois]",
"Ecole nationale sup&eacute;rieure de m&eacute;canique et d'a&eacute;rotechnique de Poitiers		[86 - Futuroscope]",
"Ecole nationale sup&eacute;rieure de m&eacute;canique et des microtechniques de Besan&ccedil;on	[25 - Besan&ccedil;on]",
"Ecole nationale sup&eacute;rieure de physique, &eacute;lectronique et mat&eacute;riaux	[38 - Grenoble]",

"Ecole nationale sup&eacute;rieure de techniques avanc&eacute;es	[91 - Palaiseau]",
"Ecole nationale sup&eacute;rieure de techniques avanc&eacute;es Bretagne	[29 - Brest]",
"Ecole nationale sup&eacute;rieure de technologie des biomol&eacute;cules de Bordeaux		[33 - Bordeaux]",
"Ecole nationale sup&eacute;rieure des arts et industries textiles	[59 - Roubaix]",
"Ecole nationale sup&eacute;rieure des industries chimiques	[54 - Nancy]",
"Ecole nationale sup&eacute;rieure des ing&eacute;nieurs en arts chimiques et technologiques	[31 - Toulouse]",
"Ecole nationale sup&eacute;rieure des ing&eacute;nieurs Sud Alsace	[68 - Mulhouse]",

"Ecole nationale sup&eacute;rieure des sciences agronomiques de Bordeaux Aquitaine	[33 - Gradignan]",
"Ecole nationale sup&eacute;rieure des sciences appliqu&eacute;es et de technologie	[22 - Lannion]",
"Ecole nationale sup&eacute;rieure des technologies et industries du bois	[88 - Epinal]",
"Ecole nationale sup&eacute;rieure en environnement, g&eacute;oressources et ing&eacute;nierie du d&eacute;veloppement durable	[33 - Pessac]",
"Ecole nationale sup&eacute;rieure en g&eacute;nie des syst&egrave;mes industriels	[54 - Nancy]",
"Ecole nationale sup&eacute;rieure en g&eacute;nie des technologies industrielles	[64 - Pau]",
"Ecole nationale sup&eacute;rieure en syst&egrave;mes avanc&eacute;s et r&eacute;seaux	[26 - Valence]",

"Ecole nationale sup&eacute;rieure maritime	[76 - Havre]",
"Ecole nationale sup&eacute;rieure maritime	[13 - Marseille]",
"Ecole nationale sup&eacute;rieure maritime	[44 - Nantes]",
"Ecole nationale sup&eacute;rieure maritime	[75 - Paris]",
"Ecole nationale sup&eacute;rieure maritime	[35 - Saint-Malo]",

"Ecole nationale v&eacute;t&eacute;rinaire, agroalimentaire et de l'alimentation, de Nantes (ONIRIS V&eacute;to)	[44 - Nantes]",

"Ecole navale	[29 - Lanv&eacute;oc-Poulmic]",

"Ecole polytechnique (X)	[91 - Palaiseau]",

"Ecole pour l'informatique et les techniques avanc&eacute;es	[94 - Le Kremlin-Bic&ecirc;tre]",
"Ecole sp&eacute;ciale de m&eacute;canique et d'&eacute;lectricit&eacute;	[94 - Ivry-sur-Seine]",
"Ecole sp&eacute;ciale des travaux publics, du b&acirc;timent et de l'industrie	[94 - Cachan]",
"Ecole sp&eacute;ciale militaire de Saint-Cyr	[56 - Guer]",
"Ecole sup&eacute;rieure angevine en informatique et productique	[49 - Angers]", 
"Ecole sup&eacute;rieure angevine en informatique et productique	[49 - Saint-Barth&eacute;lemy-d'Anjou]", 
"Ecole sup&eacute;rieure angevine en informatique et productique	[06 - Grasse]", 

"Ecole sup&eacute;rieure chimie physique &eacute;lectronique de Lyon		[69 - Villeurbanne]",
"Ecole sup&eacute;rieure d'agriculture d'Angers	[49 - Angers]",
"Ecole sup&eacute;rieure d'informatique et applications de Lorraine	[54 - Vandœuvre]",
"Ecole sup&eacute;rieure d'informatique, &eacute;lectronique, automatique	[75 - Paris]", 
"Ecole sup&eacute;rieure d'informatique, &eacute;lectronique, automatique	[53 - Laval]",

"Ecole sup&eacute;rieure d'ing&eacute;nieurs de l'universit&eacute; de Cherbourg-Octeville [50 - Cherbourg-Octeville]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs de l'universit&eacute; de Caen Basse-Normandie	[14 - Caen]",

"Ecole sup&eacute;rieure d'ing&eacute;nieurs de recherche en mat&eacute;riaux et en infotronique	[21 - Dijon]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs de Reims		[51 - Reims]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs de Rennes	[35 - Rennes]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs des travaux de la construction de Cachan		[94 - Cachan]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs des travaux de la construction de Caen		[14 - Epron]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs des travaux de la construction de Metz		[57 - Metz]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs en agroalimentaire de Bretagne atlantique	[29 - Plouzan&eacute;]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs en d&eacute;veloppement agroalimentaire int&eacute;gr&eacute;		[97 - Saint-Denis]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs en g&eacute;nie &eacute;lectrique		[76 - Saint-&eacute;tienne-du-Rouvray]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs en informatique et g&eacute;nie des t&eacute;l&eacute;communications		[77 - Avon-Fontainebleau]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs en &eacute;lectronique et &eacute;lectrotechnique d'Amiens	[80 - Amiens]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs en &eacute;lectronique et &eacute;lectrotechnique de Paris	[93 - Noisy-le-Grand]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs et de techniciens pour l'agriculture	[76 - Mont-Saint-Aignan]",
"Ecole sup&eacute;rieure d'ing&eacute;nieurs L&eacute;onard-de-Vinci		[92 - Paris-La D&eacute;fense]",

"Ecole sup&eacute;rieure d'optique	[91 - Orsay]",

"Ecole sup&eacute;rieure d'&eacute;lectricit&eacute;	[91 - Gif-sur-Yvette]", 
"Ecole sup&eacute;rieure d'&eacute;lectricit&eacute;	[35 - Rennes]",
"Ecole sup&eacute;rieure d'&eacute;lectricit&eacute;	[57 - Metz]",

"Ecole sup&eacute;rieure d'&eacute;lectronique de l'Ouest	[49 - Angers]",
"Ecole sup&eacute;rieure de biotechnologie Strasbourg	[67 - Illkirch-Graffenstaden]",
"Ecole sup&eacute;rieure de chimie organique et min&eacute;rale	[60 - Compi&egrave;gne]",
"Ecole sup&eacute;rieure de fonderie et de forge en convention avec l'Institut sup&eacute;rieur de m&eacute;canique de Paris		[92 - S&egrave;vre]",
"Ecole sup&eacute;rieure de physique et de chimie industrielles de la ville de Paris	[75 - Paris]",
"Ecole sup&eacute;rieure des g&eacute;om&egrave;tres et topographes	[72 - Le Mans]",
"Ecole sup&eacute;rieure des sciences et technologies de l'ing&eacute;nieur de Nancy	[54 - Vandœuvre]",
"Ecole sup&eacute;rieure des techniques a&eacute;ronautiques et de construction automobile	[92 - Levallois-Perret]", 
"Ecole sup&eacute;rieure des techniques a&eacute;ronautiques et de construction automobile	[53 - Laval]", 
"Ecole sup&eacute;rieure des technologies industrielles avanc&eacute;es	[64 - Bayonne]",
"Ecole sup&eacute;rieure du bois	[44 - Nantes]",

"EPF	[92 - Sceaux]",
"Groupe Institut sup&eacute;rieur d'agriculture de Lille	[06 - Antibes]",
"Groupe Institut sup&eacute;rieur d'agriculture de Lille	[59 - Lille]",

"Hautes &eacute;tudes d'ing&eacute;nieur	[59 - Lille]",

"Institut catholique d'arts et m&eacute;tiers	[59 - Lille]", 
"Institut catholique d'arts et m&eacute;tiers	[85 - La Roche-sur-Yon]",
"Institut catholique d'arts et m&eacute;tiers	[44 - Nantes]",
"Institut catholique d'arts et m&eacute;tiers	[75 - Paris]",
"Institut catholique d'arts et m&eacute;tiers	[31 - Toulouse]",
"Institut catholique d'arts et m&eacute;tiers	[56 - Vannes]",

"Institut d'enseignement sup&eacute;rieur et de recherche en alimentation, sant&eacute; animale, sciences agronomiques et de l'environnement	[63 - Lempdes]",
"Institut d'ing&eacute;nierie informatique de Limoges	[87 - Limoges]", 
"Institut d'ing&eacute;nierie informatique de Limoges	[12 - Rodez]", 
"Institut des Sciences de l'Ing&eacute;nieur de Toulon et du Var	[83 - La Valette]",
"Institut des sciences et industries du vivant et de l'environnement	[54 - Nancy]",
"Institut des sciences et industries du vivant et de l'environnement	[75 - Paris]",
"Institut des sciences et techniques de l'ing&eacute;nieur d'Angers	[49 - Angers]",
"Institut des sciences et techniques des Yvelines	[78 - Versailles]",
"Institut fran&ccedil;ais de m&eacute;canique avanc&eacute;e	[63 - Aubi&egrave;re]",

"Institut Galil&eacute;e	[93 - Villetaneuse]",

"Institut national des sciences appliqu&eacute;es de Lyon	[69 - Villeurbanne]",
"Institut national des sciences appliqu&eacute;es de Rennes	[35 - Rennes]",
"Institut national des sciences appliqu&eacute;es de Rouen	[76 - Mont-Saint-Aignan]",
"Institut national des sciences appliqu&eacute;es de Strasbourg	[67 - Strasbourg]",
"Institut national des sciences appliqu&eacute;es de Toulouse	[31 - Toulouse]",
"Institut national sup&eacute;rieur des sciences agronomiques, de l'alimentation et de l'environnement	[21 - Dijon]",
"Institut national polytechnique de Toulouse	[31 - Toulouse]",

"Institut polytechnique de Grenoble	[38 - Grenoble]",
"Institut polytechnique des sciences avanc&eacute;es	[94 - Ivry-sur-Seine]",
"Institut polytechnique LaSalle Beauvais	[60 - Beauvais]",

"Institut sup&eacute;rieur d'agriculture et d'agroalimentaire Rh&ocirc;ne-Alpes	[69 - Lyon]",
"Institut sup&eacute;rieur d'informatique, de mod&eacute;lisation et de leurs applications	[63 - Aubi&egrave;re]",
"Institut sup&eacute;rieur d'ing&eacute;nieurs de Franche-Comt&eacute;	[25 - Besan&ccedil;on]",
"Institut sup&eacute;rieur d'&eacute;lectronique de Paris	[75 - Paris]",
"Institut sup&eacute;rieur d'&eacute;tudes logistiques	[76 - Le Havre]",
"Institut sup&eacute;rieur de l'automobile et des transports	[58 - Nevers]",
"Institut sup&eacute;rieur de l'a&eacute;ronautique et de l'espace	[31 - Toulouse]",
"Institut sup&eacute;rieur de l'&eacute;lectronique et du num&eacute;rique	[59 - Lille]",
"Institut sup&eacute;rieur de l'&eacute;lectronique et du num&eacute;rique	[83 - Toulon]",
"Institut sup&eacute;rieur de l'&eacute;lectronique et du num&eacute;rique	[29 - Brest]",
"Institut sup&eacute;rieur de m&eacute;canique de Paris	[93 - Saint-Ouen]",
"Institut sup&eacute;rieur de m&eacute;canique de Paris	[83 - Toulon]",
"Institut sup&eacute;rieur de plasturgie d'Alen&ccedil;on	[61 - Alen&ccedil;on]",
"Institut sup&eacute;rieur des mat&eacute;riaux et m&eacute;caniques avanc&eacute;es	[72 - Le Mans]",
"Institut sup&eacute;rieur des sciences agronomiques, agroalimentaires, horticoles et du paysage	[49 - Angers]",
"Institut sup&eacute;rieur des sciences agronomiques, agroalimentaires, horticoles et du paysage	[35 - Rennes]",

"Institut textile et chimique	[69 - &eacute;cully]",

"Paoli Tech	[20 - Corse]",

"Polytech' universitaire d'Orl&eacute;ans	[45 - Orl&eacute;ans]",
"Polytech' universitaire de Nantes	[44 - Nantes]",
"Polytech' universitaire de Grenoble I	[38 - Grenoble]",
"Polytech' universitaire de Lyon-I	[69 - Villeurbanne]",
"Polytech' universitaire de Lille	[59 - Villeneuve-d'Ascq]",
"Polytech' universitaire de Marseille	[13 - Marseille]",
"Polytech' universitaire de Montpellier	[34 - Montpellier]",
"Polytech' universitaire Pierre et Marie Curie de l'universit&eacute; Paris VI	[75 - Paris]",
"Polytech' Paris-Sud	[91 - Orsay]",
"Polytech' Clermont-Ferrand	[63 - Aubi&egrave;re]",
"Polytech' Nice-Sophia	[06 - Sophia-Antipolis]",
"Polytech' Savoie	[74 - Annecy]",
"Polytech' Tours	[37 - Tours]",
"T&eacute;l&eacute;com Lille	[59 - Villeneuve-d'Ascq]",
"Telecom Saint-&eacute;tienne	[42 - Saint-&eacute;tienne]",
"T&eacute;l&eacute;com Bretagne	[29 - Plouzan&eacute;]",
"T&eacute;l&eacute;com ParisTech	[75 - Paris]",
"T&eacute;l&eacute;com ParisTech	[06 - Sophia-Antipolis]",
"T&eacute;l&eacute;com Physique Strasbourg	[67 - Illkirch-Graffenstaden]",
"T&eacute;l&eacute;com SudParis	[91 - Evry ]"
);



$liste_ecoles_universites = array(

/* Universit&eacute;s  */




"Science Po Dijon	[21 - Dijon]",
"Science Po Havre	[76 - Le Havre]",
"Science Po Menton	[06 - Menton]",
"Science Po Nancy	[54 - Nancy]",
"Science Po Poitiers	[86 - Poitiers]",
"Science Po Paris	[75 - Paris]",
"Science Po Reims	[51 - Reims]",

"Institut d’&eacute;tudes politiques d’Aix-en-Provence	[13 - Aix-en-provence]",
"Institut d’&eacute;tudes politiques de Bordeaux	[33 - Bordeaux]",
"Institut d’&eacute;tudes politiques de Grenoble	[38 - Grenoble]",
"Institut d’&eacute;tudes politiques de Lille		[59 - Lille]",
"Institut d’&eacute;tudes politiques de Lyon		[69 - Lyon]",
"Institut d’&eacute;tudes politiques de Rennes		[35 - Rennes]",
"Institut d’&eacute;tudes politiques de Strasbourg 	[67 - Strasbourg]",
"Institut d’&eacute;tudes politiques de Toulouse	[31 - Toulouse]",


"Sorbonne [75 - Paris]",
"Universit&eacute; d'Aix-Marseille (I,II,III) 	[83 - Aix-en-provence]",
"Universit&eacute; d'Amiens	[80 - Amiens]",
"Universit&eacute; d'Angers	[49 - Angers]",
"Universit&eacute; des Antilles-Guyane		[971 - Antilles, 973 - Guyane]",
"Universit&eacute; d'Artois 	[62 - Artois]",
"Universit&eacute; d'Avignon 	 [84 - Avignon]",
"Universit&eacute; de Besan&ccedil;on 	[25 - Besan&ccedil;on]",
"Universit&eacute; de Bordeaux-I  	[33 - Bordeaux]",
"Universit&eacute; de Bordeaux-II 	[33 - Bordeaux]",
"Universit&eacute; de Bordeaux-III	[33 - Bordeaux]",
"Universit&eacute; de Bordeaux-IV	[33 - Bordeaux]",
"Universit&eacute; de Brest	[29 - Brest]",
"Universit&eacute; de Bretagne-Sud	[56 - Lorient]",
"Universit&eacute; de Caen	[14 - Caen]",
"Universit&eacute; de Cergy-Pontoise	[95 - Cergy-Pontoise]",
"Universit&eacute; de Chamb&eacute;ry		[73 - Chamb&eacute;ry]",
"Universit&eacute; de Clermont-Ferrand-I	[63 - Clermont-Ferrand]",
"Universit&eacute; de Clermont-Ferrand-II	[63 - Clermont-Ferrand]",
"Universit&eacute; de Corse	[20 - Corte]",
"Universit&eacute; de Dijon	[21 - Dijon]",
"Universit&eacute; de Evry-Val d’Essonne	[91 - Evry-Val d'Essonne]",
"Universit&eacute; de Grenoble-I	[38 - Grenoble]",
"Universit&eacute; de Grenoble-II	[38 - Grenoble]",
"Universit&eacute; de Grenoble-III	[38 - Grenoble]",
"Universit&eacute; de La R&eacute;union	[974 - La R&eacute;union]",
"Universit&eacute; de La Rochelle	[17 - La Rochelle]",
"Universit&eacute; du Havre	[76 - Le Havre]",
"Universit&eacute; du Mans	[72 - Le Mans]",
"Universit&eacute; de Lille-I	[59 - Lille]",
"Universit&eacute; de Lille-II	[59 - Lille]",
"Universit&eacute; de Lille-III	[59 - Lille]",
"Universit&eacute; de Limoges	[87 - Limoges]",
"Universit&eacute; du Littoral	[59 - Dunkerque]",
"Universit&eacute; de Lyon-I	[69 - Lyon]",
"Universit&eacute; de Lyon-II	[69 - Lyon]",
"Universit&eacute; de Lyon-III	[69 - Lyon]",
"Universit&eacute; de Marne-la-Vall&eacute;e	[77 - Marne-la-Vall&eacute;e]",
"Universit&eacute; de Montpellier-I	[34 - Montpellier]",
"Universit&eacute; de Montpellier-II	[34 - Montpellier]",
"Universit&eacute; de Montpellier-III	[34 - Montpellier]",
"Universit&eacute; de Mulhouse	[68 - Lulhouse]",
"Universit&eacute; de Nantes	[44 - Nantes]",
"Universit&eacute; de Nice	[06 - Nice]",
"Universit&eacute; de N&icirc;mes	[30 - N&icirc;mes]",
"Universit&eacute; de Nouvelle-Cal&eacute;donie	[988 - Nouvelles Cal&eacute;donie]",
"Universit&eacute; d'Orl&eacute;ans	[45 - Orl&eacute;ans]",
"Universit&eacute; de Paris-I	[75 - Paris]",
"Universit&eacute; de Paris-II	[75 - Paris]",
"Universit&eacute; de Paris-III	[75 - Paris]",
"Universit&eacute; de Paris-IV	[75 - Paris]",
"Universit&eacute; de Paris-V	[75 - Paris]",
"Universit&eacute; de Paris-VI	[75 - Paris]",
"Universit&eacute; de Paris-VII	[75 - Paris]",
"Universit&eacute; de Paris-VIII	[93 - Saint-Denis]",
"Universit&eacute; de Paris-X	[92 - Naterre]",
"Universit&eacute; de Paris-XI	[91 - Orsay]",
"Universit&eacute; de Paris-XII	[94 - Cr&eacute;teil]",
"Universit&eacute; de Paris-XIII	[93 - Villetaneuse]",
"Universit&eacute; Paris-Est Marne-la-Vall&eacute;e	[93 - Noisy-le-Grand]",
"Universit&eacute; Paris-Est Marne-la-Vall&eacute;e	[77 - Marne-la-Vall&eacute;e]",
"Universit&eacute; de Pau	[64 - Pau]",
"Universit&eacute; de Perpignan	[66 - Perpignan]",
"Universit&eacute; de Poitiers	[86 - Poitiers]",
"Universit&eacute; de Polyn&eacute;sie fran&ccedil;aise	[987 - Poly&eacute;nise Fran&ccedil;aise]",
"Universit&eacute; de Reims	[51 - Reims]",
"Universit&eacute; de Rennes-I	[35 - Rennes]",
"Universit&eacute; de Rennes-II	[35 - Rennes]",
"Universit&eacute; de Rouen	[76 - Rouen]",
"Universit&eacute; de Saint-Etienne	[42 - Saint-Etienne]",
"Universit&eacute; de Strasbourg(I,II,III)	[67 - Strasbourg]",
"Universit&eacute; de technologie de Belfort-Montb&eacute;liard	[90 - Belfort]",
"Universit&eacute; de technologie de Compi&egrave;gne	[60 - Compi&egrave;gne]",
"Universit&eacute; de technologie de Troyes	[10 - Troyes]",
"Universit&eacute; de Toulon	[83 - Toulon]",
"Universit&eacute; de Toulouse-I	[31 - Toulouse]",
"Universit&eacute; de Toulouse-II	[31 - Toulouse]",
"Universit&eacute; de Toulouse-III	[31 - Toulouse]",
"Universit&eacute; de Tours	[37 - Tours]",
"Universit&eacute; de Valenciennes	[59 - Valenciennes]",
"Universit&eacute; de Versailles-Saint-Quentin-en-Yvelines	[78 - Versailles/Saint-Quentin-en-Yvelines]"
);




$liste_ecoles_commerce = array(


/*  Ecoles de Commerce  */



"Advancia-Negocia	[75 - Paris]",
"Audencia	[44 - Nantes]",
"Bordeaux Ecole de management	[33 - Bordeaux]",
"Ecole de management de Lyon — Business School	[69 - Lyon]",
"Ecole de management de Normandie (Caen)	[14 - Caen]",
"Ecole de management de Normandie (Deauville)	[14 - Deauville]",
"Ecole de management de Normandie (Le Havre)	[76 - Le Havre]",
"Ecole de management Strasbourg		[67 - Strasbourg]",
"EDHEC Business School		[59 - Lille]",
"Ecole des dirigeants et cr&eacute;ateurs d'entreprise		[75 - Paris]",
"Ecole sup&eacute;rieure de commerce et de management de Tours-Poitiers 	[37 - Tours]",
"Ecole sup&eacute;rieure de commerce et de management de Tours-Poitiers 	[86 - Poitiers]",
"Ecole sup&eacute;rieure du commerce ext&eacute;rieur	[75 - Paris]",
"Ecole sup&eacute;rieure de commerce d'Amiens	[80 - Amiens]",
"Ecole sup&eacute;rieure de commerce de Chamb&eacute;ry Savoie	[73 - Chamb&eacute;ry]",
"Ecole sup&eacute;rieure de commerce de Clermont-Ferrand	[60 - Clermont-Ferrand]",
"Ecole sup&eacute;rieure de commerce de Dijon	[21 - Dijon]",
"Grenoble Ecole de management	[38 - Grenoble]",
"Ecole sup&eacute;rieure de commerce de La Rochelle	[17 - La Rochelle]",
"Groupe Sup de Co Montpellier Business School	[34 - Montpellier]",
"Ecole sup&eacute;rieure de commerce de Paris 	[75 - Paris]",
"Groupe Ecole sup&eacute;rieure de commerce de Pau	[64 - Pau]",
"Ecole sup&eacute;rieure de commerce de Reims	[51 - Reims]",
"Ecole sup&eacute;rieure de commerce de Rennes	[35 - Rennes]",
"Ecole sup&eacute;rieure de commerce de Rouen	[76 - Rouen]",
"Ecole sup&eacute;rieure de commerce de Saint-&eacute;tienne	[42 - Saint-Etienne]",
"Groupe ESC Toulouse	[31 - Toulouse]",
"Groupe Ecole sup&eacute;rieure de commerce de Troyes	[10 - Troyes]",
"ESG Management School	[75 - Paris]",
"Ecole sup&eacute;rieure des sciences commerciales d'Angers	[49 - Angers]",
"Ecole sup&eacute;rieure des sciences &eacute;conomiques et commerciales	[75 - Paris]",
"Ecole sup&eacute;rieure pour le d&eacute;veloppement &eacute;conomique et social	[69 - Lyon]",
"ESIEE Management	[75 - Paris]",
"Ecole sup&eacute;rieure de commerce Bretagne Brest	[29 - Brest]",
"Euromed Management	[13 - Marseille]",
"European Business School Paris	[75 - Paris]",
"Ecole des hautes &eacute;tudes commerciales de Paris	[75 - Paris]",
"ICN Business School 	[54 - Nancy]",
"I&eacute;seg School of Management	[59 - Lille]",
"Institut de pr&eacute;paration &agrave; l'administration et &agrave; la gestion	[06 - Nice]",
"Institut de pr&eacute;paration &agrave; l'administration et &agrave; la gestion	[75 - Paris]",
"Institut des hautes &eacute;tudes &eacute;conomiques et commerciales	[75 - Paris]",
"Institut europ&eacute;en d'administration des affaires	[77 - Fontainebleau]",
"Institut sup&eacute;rieur des affaires	[78 - Jouy-en-Josas]",
"Institut sup&eacute;rieur du commerce de Paris	[75 - Paris]",
"Institut sup&eacute;rieur de gestion	[75 - Paris]",
"Skema Business School	[59 - Lille]",
"Skema Business School	[75 - Paris]",
"Skema Business School	[06 - Sophia Antipolis]",
"T&eacute;l&eacute;com Ecole de Management	[91 - Evry]"


);

?>