<?php

namespace GBE\PresentationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterEmailRepository extends EntityRepository
{
}
