<?php

namespace GBE\PresentationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoutesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutesRepository extends EntityRepository
{
	public function findAllRoutes() {
		return $routes = $this->createQueryBuilder('r')
					->getQuery()
					->getResult();
	}
}
