gbe_presentation_homepage:
    pattern:  /
    defaults: { _controller: GBEPresentationBundle:Presentation:index }

gbe_presentation_presentation:
    pattern:  /presentation
    defaults: { _controller: GBEPresentationBundle:Presentation:presentation }

gbe_presentation_bio:
    pattern:  /bio
    defaults: { _controller: GBEPresentationBundle:Presentation:bio }

gbe_presentation_history:
    pattern:  /history
    defaults: { _controller: GBEPresentationBundle:Presentation:history }

gbe_presentation_route:
    pattern:  /route
    defaults: { _controller: GBEPresentationBundle:Route:route }

gbe_presentation_route_delete:
    pattern:  /route/delete
    defaults: { _controller: GBEPresentationBundle:Route:removeRoute }

gbe_presentation_calendar:
    pattern:  /calendar
    defaults: { _controller: GBEPresentationBundle:Route:calendar }

gbe_presentation_partners:
    pattern:  /partners
    defaults: { _controller: GBEPresentationBundle:Media:partners }

gbe_presentation_media:
    pattern:  /media
    defaults: { _controller: GBEPresentationBundle:Media:media }

gbe_presentation_photos:
    pattern:  /photos
    defaults: { _controller: GBEPresentationBundle:Photos:photos }

gbe_presentation_add_photos:
    pattern:  /photos/add
    defaults: { _controller: GBEPresentationBundle:Photos:add }

gbe_presentation_photos_routes:
    pattern:  /photos/{routesId}
    defaults: { _controller: GBEPresentationBundle:Photos:photosRoutes }
    requirements:
        routesId: \d*

gbe_presentation_contact:
    pattern:  /contact
    defaults: { _controller: GBEPresentationBundle:Contact:contact }

gbe_presentation_send:
    pattern:  /send
    defaults: { _controller: GBEPresentationBundle:Contact:send }

gbe_presentation_live:
    pattern:  /live
    defaults: { _controller: GBEPresentationBundle:Live:live }

gbe_presentation_newsletter:
    path:     /newsletter
    defaults: { _controller: GBEPresentationBundle:Presentation:Newsletter }

gbe_user_team_see:
    pattern:  /team/{teamId}
    defaults: { _controller: GBEUserBundle:User:teamSee }


