gbe_user_homepage:
    pattern:  /
    defaults: { _controller: GBEUserBundle:User:indexUser }

gbe_user_edit:
    pattern:  /edit/infos
    defaults: { _controller: GBEUserBundle:User:editUser }

gbe_user_editAvatar:
    pattern:  /edit/avatar
    defaults: { _controller: GBEUserBundle:User:editAvatar }

gbe_user_editPassword:
    pattern:  /edit/password
    defaults: { _controller: GBEUserBundle:User:editPassword }

gbe_user_selectRoute:
    pattern:  /select/{routeId}
    defaults: { _controller: GBEUserBundle:User:selectRoute }

gbe_user_confirmRoute:
    pattern:  /confirm/{routeId}
    defaults: { _controller: GBEUserBundle:User:confirmRoute }

gbe_user_member:
    pattern:  /member/{memberId}
    defaults: { _controller: GBEUserBundle:User:memberPage }

gbe_user_team:
    pattern:  /team
    defaults: { _controller: GBEUserBundle:User:teamUser }

gbe_user_editTeamName:
    pattern:  /edit/team/name
    defaults: { _controller: GBEUserBundle:User:editTeamName }

gbe_user_admin:
    pattern:  /admin
    defaults: { _controller: GBEUserBundle:Admin:admin }

gbe_user_admin_email:
    pattern:  /admin/email/{toWho}
    defaults: { _controller: GBEUserBundle:Admin:sendEmail }

gbe_user_admin_email_sent:
    pattern:  /admin/sent
    defaults: { _controller: GBEUserBundle:Admin:sent }

gbe_user_member_delete:
    pattern:  /admin/member/delete/{memberId}
    defaults: { _controller: GBEUserBundle:Admin:deleteMember }



