gbe_user_homepage:
    pattern:  /
    defaults: { _controller: GBEUserBundle:User:indexUser }

gbe_user_team:
    pattern:  /team
    defaults: { _controller: GBEUserBundle:User:teamUser }

gbe_user_admin:
    pattern:  /admin
    defaults: { _controller: GBEUserBundle:Admin:admin }

    # "Participer"=>"pages/participer.php",
    # "Presentation"=>"pages/presentation.php",
    # "Trophees"=>"pages/trophees.php",
    # "Qui_sommes_nous"=>"pages/qui_sommes_nous.php",
    # "Parcours"=>"pages/parcours.php",
    # "Partenaires"=>"pages/partenaires.php",
    # "Nous_suivre"=>"pages/nous_suivre.php",
    # "Photos"=>"pages/photos.php",
    # "Contact"=>"pages/contact.php",
    # "Contact_Organisation"=>"pages/contact_organisation.php",
    # "Contact_Chef_Equipe"=>"pages/contact_chef_equipe.php",
    # "Contact_Traitement"=>"pages/contact-traitement.php",
    # "Profil"=>"espace_membre/profil.php",
    # "Inscription"=>"espace_membre/inscription.php",
    # "Faire_Don"=>"pages/faire_don.php",
    # "Connexion"=>"espace_membre/connexion.php",
    # "Etape_"=>"pages/etape_.php",
    # "Etape_Confirmation"=>"pages/etape_confirmation.php",
    # "Choix_Troncon"=>"pages/choix_troncon.php",
    # "Presse"=>"pages/presse.php",
    # "Charger_Photos"=>"pages/charger_photos.php",
    # "Supprimer_Photos"=>"pages/supprimer_photos.php",
    # "Page_Profil"=>"espace_membre/page_profil.php",
    # "Edit_Avatar"=>"espace_membre/edit_avatar.php",
    # "Edit_Password"=>"espace_membre/edit_password.php",
    # "Edit_Infos"=>"espace_membre/edit_infos.php",
    # "Rejoindre_Equipe"=>"pages/rejoindre_equipe.php",
    # "Equipe"=>"pages/equipe.php",
    # "Mon_Equipe"=>"pages/mon_equipe.php",
    # "Edit_Equipe"=>"espace_membre/edit_equipe.php",
    # "Liste_Participants"=>"pages/liste_participants.php",
    # "Liste_Ecoles"=>"pages/liste_participants_ecole.php",
    # "Administration"=>"espace_membre/administration.php",
    # "Calendrier"=>"pages/calendrier.php"