<?php

namespace GBE\PresentationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PresentationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \GBE\PresentationBundle\Controller\PresentationController();
        return $instance;
    }
}
